DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
    ID           VARCHAR(100) NOT NULL,
    NAME         VARCHAR(200) NOT NULL,
    EMAIL        VARCHAR(200) NOT NULL,
    PASSWORD     VARCHAR(200) NOT NULL,
    TOKEN        VARCHAR(500) NOT NULL,
    LAST_LOGIN   DATETIME DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE    TINYINT NOT NULL,
    CREATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    UNIQUE KEY EMAIL_UNIQUE (EMAIL)
);

DROP TABLE IF EXISTS PHONE;

CREATE TABLE PHONE
(
    ID           VARCHAR(100) NOT NULL,
    USER_ID      VARCHAR(100) NOT NULL,
    NUMBER       VARCHAR(7) NOT NULL,
    CITY_CODE    VARCHAR(1) NOT NULL,
    COUNTRY_CODE VARCHAR(6) NOT NULL,
    IS_ACTIVE    TINYINT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

INSERT INTO USER(ID, NAME, EMAIL, PASSWORD, TOKEN, LAST_LOGIN, IS_ACTIVE, CREATED_AT)
VALUES ('15dfcfbd-13d7-43d0-9514-1ef7ceaa3838', 'Diego', 'diego@dominio.cl', '$2a$10$jkdXImMTw5xBUuWN5eQGje/zky5A9smzFdqT370aFSTTagtNQ/eKW',
        'eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2MzgzMTQ5NzIsInN1YiI6ImRhY2tuZ0Bkb21pbmlvLmNsIiwiZXhwIjoxNjM4MzIwOTcyfQ.ok1Pmn50ObIZLrrL9nBjqDcVFE0xk3AXXPgvZyucLmP2IJGo2OG7oitYWKCKUDlmquhxo8ZBJEv9LhFrNbTCmg'
        ,CURRENT_TIMESTAMP(), 1,
        CURRENT_TIMESTAMP());

INSERT INTO PHONE(ID, USER_ID, NUMBER, CITY_CODE, COUNTRY_CODE, IS_ACTIVE, CREATED_AT)
VALUES ('ec8ce6ab-cc9f-453b-b668-999e9b28341a', '15dfcfbd-13d7-43d0-9514-1ef7ceaa3838', '7654321', '1', '57', 1, CURRENT_TIMESTAMP());